// Bake Natural Earth 110m admin-0 countries → src/world-data.js (run once; output is committed).
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const URL =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson";

const res = await fetch(URL);
if (!res.ok) throw new Error(`fetch failed: ${res.status} ${res.statusText}`);
const gj = await res.json();

const r2 = (n) => Math.round(n * 100) / 100;
const countries = [];

for (const f of gj.features) {
  const props = f.properties;
  const name = props.NAME ?? props.ADMIN ?? props.name;
  const continent = props.CONTINENT ?? props.continent ?? "Unknown";
  if (!name || !f.geometry) continue;
  const polys =
    f.geometry.type === "Polygon" ? [f.geometry.coordinates]
    : f.geometry.type === "MultiPolygon" ? f.geometry.coordinates
    : [];
  const p = polys.map((rings) => {
    const flat = rings.map((ring) => {
      const a = [];
      for (const [lon, lat] of ring) a.push(r2(lon), r2(lat));
      return a;
    });
    let minLon = 180, minLat = 90, maxLon = -180, maxLat = -90;
    const outer = flat[0];
    for (let i = 0; i < outer.length; i += 2) {
      if (outer[i] < minLon) minLon = outer[i];
      if (outer[i] > maxLon) maxLon = outer[i];
      if (outer[i + 1] < minLat) minLat = outer[i + 1];
      if (outer[i + 1] > maxLat) maxLat = outer[i + 1];
    }
    return { b: [minLon, minLat, maxLon, maxLat], r: flat };
  });
  if (p.length) countries.push({ n: name, c: continent, p });
}

const out =
  "// GENERATED by tools/bake-data.mjs — do not edit by hand.\n" +
  "// Source: Natural Earth 110m admin-0 countries (public domain).\n" +
  `const WORLD_DATA = { countries: ${JSON.stringify(countries)} };\n` +
  '(typeof self !== "undefined" ? self : globalThis).WORLD_DATA = WORLD_DATA;\n' +
  'if (typeof module === "object" && module.exports !== undefined) module.exports = WORLD_DATA;\n';

const here = dirname(fileURLToPath(import.meta.url));
mkdirSync(join(here, "../src"), { recursive: true });
writeFileSync(join(here, "../src/world-data.js"), out);
console.log(`baked ${countries.length} countries, ${(out.length / 1024).toFixed(0)}KB`);
